name: Synchronize Wiki

on:
  schedule:
    # daily, midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  synchronize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          fetch-depth: 0
      - name: Set git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Fetch
        run: |
          git remote add upstream ${{ github.server_url }}/${{ github.repository_owner }}/heaps-doc
          git fetch upstream master
      - name: Merge
        run: |
          git merge upstream/master --no-edit
      - name: Push
        run: |
          git push
